apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - platform/api-server.yaml
  - platform/auth-server.yaml
  - frontend/frontend.yaml
  - infra/otel-collector.yaml
  - infra/gateway.yaml
  - infra/external-secrets.yaml
