/** Maps AI tool names to drawer registry component keys. */
export const CANVAS_TOOL_COMPONENT_MAP: Record<string, string> = {
  open_quote_form: 'QuoteFormDrawer',
  create_quote: 'QuoteFormDrawer',
  open_task_form: 'TaskFormDrawer',
  create_task: 'TaskFormDrawer',
  open_task: 'TaskDetailDrawer',
  view_task: 'TaskDetailDrawer',
  show_task: 'TaskDetailDrawer',
  open_contact_form: 'ContactFormDrawer',
  create_contact: 'ContactFormDrawer',
  open_appointment_form: 'AppointmentFormDrawer',
  create_appointment: 'AppointmentFormDrawer',
  open_appointment: 'AppointmentFormDrawer',
  view_appointment: 'AppointmentFormDrawer',
  show_appointment: 'AppointmentFormDrawer',
  edit_appointment: 'AppointmentFormDrawer',
  open_create_assessment: 'AssessmentCreateDrawer',
  fill_create_assessment: 'AssessmentCreateDrawer',
  open_assessment_attendance: 'AssessmentAttendanceDrawer',
  fill_assessment_attendance: 'AssessmentAttendanceDrawer',
  open_assessment_building: 'AssessmentBuildingTabDrawer',
  fill_assessment_building: 'AssessmentBuildingTabDrawer',
  open_assessment_habitability: 'AssessmentHabitabilityDrawer',
  fill_assessment_habitability: 'AssessmentHabitabilityDrawer',
  open_assessment_hazards: 'AssessmentHazardsTabDrawer',
  fill_assessment_hazards: 'AssessmentHazardsTabDrawer',
  open_assessment_damage: 'AssessmentDamageDrawer',
  fill_assessment_damage: 'AssessmentDamageDrawer',
  open_assessment_makeSafe: 'AssessmentMakeSafeDrawer',
  fill_assessment_makeSafe: 'AssessmentMakeSafeDrawer',
  open_assessment_tempAccommodation: 'AssessmentTempAccommodationDrawer',
  fill_assessment_tempAccommodation: 'AssessmentTempAccommodationDrawer',
  open_assessment_specialists: 'AssessmentSpecialistsDrawer',
  fill_assessment_specialists: 'AssessmentSpecialistsDrawer',
  open_assessment_recommendation: 'AssessmentRecommendationDrawer',
  fill_assessment_recommendation: 'AssessmentRecommendationDrawer',
};

export function resolveCanvasComponent(toolName: string): string | null {
  return CANVAS_TOOL_COMPONENT_MAP[toolName] ?? null;
}
