import {
  quoteGroups, quoteCombos, quoteItems,
  proposalGroups, proposalCombos, proposalItems,
  workOrderGroups, workOrderCombos, workOrderItems,
} from '../../../database/schema';
import type { CopyConfig } from './line-item-copy.service';

export const QUOTE_TO_PROPOSAL_CONFIG: CopyConfig = {
  sourceGroupTable: quoteGroups,
  sourceComboTable: quoteCombos,
  sourceItemTable: quoteItems,
  targetGroupTable: proposalGroups,
  targetComboTable: proposalCombos,
  targetItemTable: proposalItems,
  sourceParentFk: 'quoteId',
  targetParentFk: 'proposalId',
  sourceGroupFkOnCombo: 'quoteGroupId',
  targetGroupFkOnCombo: 'proposalGroupId',
  sourceGroupFkOnItem: 'quoteGroupId',
  targetGroupFkOnItem: 'proposalGroupId',
  sourceComboFkOnItem: 'quoteComboId',
  targetComboFkOnItem: 'proposalComboId',
  groupFieldMap: {
    groupLabelLookupId: 'groupLabelLookupId',
    description: 'description',
    dimensions: 'dimensions',
    sortIndex: 'sortIndex',
    totals: 'totals',
  },
  comboFieldMap: {
    name: 'name',
    description: 'description',
    category: 'category',
    subCategory: 'subCategory',
    quantity: 'quantity',
    sortIndex: 'sortIndex',
    totals: 'totals',
    comboPayload: 'comboPayload',
  },
  itemFieldMap: {
    unitTypeLookupId: 'unitTypeLookupId',
    name: 'name',
    description: 'description',
    category: 'category',
    subCategory: 'subCategory',
    itemType: 'itemType',
    quantity: 'quantity',
    tax: 'tax',
    unitCost: 'unitCost',
    sortIndex: 'sortIndex',
    note: 'note',
    totals: 'totals',
  },
  itemFilter: (item) => item.internal !== true,
};

export const QUOTE_TO_WORK_ORDER_CONFIG: CopyConfig = {
  sourceGroupTable: quoteGroups,
  sourceComboTable: quoteCombos,
  sourceItemTable: quoteItems,
  targetGroupTable: workOrderGroups,
  targetComboTable: workOrderCombos,
  targetItemTable: workOrderItems,
  sourceParentFk: 'quoteId',
  targetParentFk: 'workOrderId',
  sourceGroupFkOnCombo: 'quoteGroupId',
  targetGroupFkOnCombo: 'workOrderGroupId',
  sourceGroupFkOnItem: 'quoteGroupId',
  targetGroupFkOnItem: 'workOrderGroupId',
  sourceComboFkOnItem: 'quoteComboId',
  targetComboFkOnItem: 'workOrderComboId',
  groupFieldMap: {
    groupLabelLookupId: 'groupLabelLookupId',
    description: 'description',
    dimensions: 'dimensions',
    sortIndex: 'sortIndex',
    totals: 'totals',
  },
  comboFieldMap: {
    catalogComboId: 'catalogComboId',
    name: 'name',
    description: 'description',
    category: 'category',
    subCategory: 'subCategory',
    quantity: 'quantity',
    sortIndex: 'sortIndex',
    totals: 'totals',
    comboPayload: 'comboPayload',
  },
  itemFieldMap: {
    catalogItemId: 'catalogItemId',
    unitTypeLookupId: 'unitTypeLookupId',
    name: 'name',
    description: 'description',
    category: 'category',
    subCategory: 'subCategory',
    itemType: 'itemType',
    quantity: 'quantity',
    tax: 'tax',
    unitCost: 'unitCost',
    buyCost: 'buyCost',
    markupType: 'markupType',
    markupValue: 'markupValue',
    sortIndex: 'sortIndex',
    note: 'note',
    tags: 'tags',
    totals: 'totals',
  },
};
