import { AgentRole } from '../../../modules/system-agents/agent-roles';
import type { CategoryConfig, FilesystemTemplateKind } from '../../schema';

const YEARS_7 = 2555;
const YEARS_5 = 1825;
const DAYS_90 = 90;

export interface SeededCategoryNode {
  displayName: string;
  slug: string;
  description: string;
  sortOrder: number;
  config?: CategoryConfig;
  children?: SeededCategoryNode[];
}

export interface SeededFilesystemTemplatePipeline {
  name: string;
  description: string;
  triggerOn: string;
  sortOrder: number;
  categorySlug: string | null;
  steps: Array<{ agentId: string; stepOrder: number; config?: Record<string, unknown> }>;
}

export interface SeededFilesystemTemplate {
  /** Stable name used for idempotent upsert of platform templates. */
  name: string;
  description: string;
  kind: FilesystemTemplateKind;
  /** Only the company starter is the org setup default. */
  isDefault: boolean;
  categories: SeededCategoryNode[];
  pipelines: SeededFilesystemTemplatePipeline[];
}

const CLASSIFY_PIPELINE: SeededFilesystemTemplatePipeline = {
  name: 'Classify on upload',
  description:
    'Runs the doc-classifier agent when a document upload completes so files are auto-filed using category descriptions.',
  triggerOn: 'upload_complete',
  sortOrder: 0,
  categorySlug: null,
  steps: [{ agentId: AgentRole.DOCUMENT_CLASSIFIER, stepOrder: 0, config: {} }],
};

/**
 * Org-wide company filesystem — policies, corporate records, vendor master.
 * Keep lean; descriptions are classifier prompts.
 */
export const COMPANY_FILESYSTEM_TEMPLATE: SeededFilesystemTemplate = {
  name: 'Company',
  kind: 'company',
  isDefault: true,
  description:
    'Organisation-wide document folders — compliance, finance, HR, vendor master, and templates. ' +
    'Not for job/site packs (use a Project template for those).',
  pipelines: [CLASSIFY_PIPELINE],
  categories: [
    {
      displayName: 'Company & Compliance',
      slug: 'COMPANY_COMPLIANCE',
      description:
        'Corporate licences, builder registration, insurance certificates of currency, WHS policies, ' +
        'and company-level compliance packs. Do NOT file job-specific make-safe or site SWMS here — those belong on a Project filesystem.',
      sortOrder: 0,
      config: { color: '#2563eb', retentionDays: YEARS_7 },
    },
    {
      displayName: 'Finance & Admin',
      slug: 'FINANCE_ADMIN',
      description:
        'Bank details, tax/GST records, corporate contracts, and office admin documents. ' +
        'Do NOT file job client invoices or supplier bills for a specific job here.',
      sortOrder: 1,
      config: { color: '#ca8a04', retentionDays: YEARS_7 },
    },
    {
      displayName: 'HR & People',
      slug: 'HR_PEOPLE',
      description:
        'Employee records, inductions, training certificates, and HR correspondence. ' +
        'Do NOT file subcontractor agreements for a specific job here — use Vendor Master or the Project filesystem.',
      sortOrder: 2,
      config: { color: '#7c3aed', retentionDays: YEARS_7 },
    },
    {
      displayName: 'Vendor Master',
      slug: 'VENDOR_MASTER',
      description:
        'Standing supplier/subcontractor agreements, certificates of currency, and preferred-vendor packs. ' +
        'Do NOT file purchase orders, RFQs, or bills for a specific job — those belong on a Project filesystem.',
      sortOrder: 3,
      config: { color: '#0891b2', retentionDays: YEARS_5 },
    },
    {
      displayName: 'Templates & Forms',
      slug: 'TEMPLATES_FORMS',
      description:
        'Blank forms, letterheads, scope templates, and reusable document templates. ' +
        'Do NOT file completed/filled forms for a job here.',
      sortOrder: 4,
      config: { color: '#64748b', retentionDays: YEARS_5 },
    },
    {
      displayName: 'Correspondence',
      slug: 'CORRESPONDENCE',
      description:
        'General company correspondence not tied to a single job (e.g. insurer panel letters, landlord MOUs). ' +
        'Job-specific insurer/insured emails belong on a Project filesystem.',
      sortOrder: 5,
      config: { color: '#94a3b8', retentionDays: YEARS_5 },
    },
    {
      displayName: 'AI Exports',
      slug: 'AI_EXPORTS',
      description:
        'Artifacts generated by AI for company-level use. Do NOT file source claim or site documents here.',
      sortOrder: 6,
      config: { color: '#ec4899', retentionDays: DAYS_90 },
    },
    {
      displayName: 'Other',
      slug: 'OTHER',
      description:
        'Catch-all when no other company category fits. Prefer a more specific category when possible.',
      sortOrder: 7,
      config: { color: '#a3a3a3', retentionDays: YEARS_5 },
    },
  ],
};

/**
 * Per-job (project) filesystem — mirrors the Job detail menu: estimates, WOs,
 * invoices, RFQs/POs/bills, site evidence, reports, correspondence.
 */
export const PROJECT_FILESYSTEM_TEMPLATE: SeededFilesystemTemplate = {
  name: 'Project',
  kind: 'project',
  isDefault: false,
  description:
    'Per-job document folders aligned with the Jobs workspace — intake, assessments, estimates, ' +
    'site evidence, works, procurement, invoices, and correspondence.',
  pipelines: [CLASSIFY_PIPELINE],
  categories: [
    {
      displayName: 'Intake',
      slug: 'INTAKE',
      description:
        'Job/claim intake: FNOL, letter of authority, policy extracts, site access instructions, and job instructions. ' +
        'Do NOT file builder assessments, quotes, or site photos here.',
      sortOrder: 0,
      config: { color: '#2563eb', retentionDays: YEARS_7 },
    },
    {
      displayName: 'Assessments & Reports',
      slug: 'ASSESSMENTS_REPORTS',
      description:
        'Builder assessments, specialist reports (engineer, hygienist, asbestos), make-safe reports, and completion reports. ' +
        'Do NOT file estimates/quotes or purchase orders here.',
      sortOrder: 1,
      config: { color: '#7c3aed', retentionDays: YEARS_7 },
    },
    {
      displayName: 'Estimates & Scope',
      slug: 'ESTIMATES_SCOPE',
      description:
        'Scope of works, customer estimates/quotes, and variations (Job → Estimates). ' +
        'Do NOT file RFQs to vendors or purchase orders here.',
      sortOrder: 2,
      config: { color: '#d97706', retentionDays: YEARS_7 },
    },
    {
      displayName: 'Site Evidence',
      slug: 'SITE_EVIDENCE',
      description:
        'Site photos, videos, moisture/thermal readings, and before/after evidence. ' +
        'Do NOT file written assessment reports here.',
      sortOrder: 3,
      config: { color: '#059669', retentionDays: YEARS_7 },
    },
    {
      displayName: 'Works & Compliance',
      slug: 'WORKS_COMPLIANCE',
      description:
        'Work orders, permits, SWMS/safety docs, progress records, and practical completion (Job → Work Orders). ' +
        'Do NOT file supplier invoices or customer invoices here.',
      sortOrder: 4,
      config: { color: '#dc2626', retentionDays: YEARS_7 },
    },
    {
      displayName: 'Procurement',
      slug: 'PROCUREMENT',
      description:
        'Vendor RFQs, proposals, purchase orders, and supplier bills (Job → RFQs / Proposals / POs / Bills). ' +
        'Do NOT file customer-facing estimates or client invoices here.',
      sortOrder: 5,
      config: { color: '#0891b2', retentionDays: YEARS_7 },
    },
    {
      displayName: 'Invoices',
      slug: 'INVOICES',
      description:
        'Client/insurer invoices and remittance advices for this job (Job → Invoices). ' +
        'Do NOT file supplier bills — those are Procurement.',
      sortOrder: 6,
      config: { color: '#ca8a04', retentionDays: YEARS_7 },
    },
    {
      displayName: 'Correspondence',
      slug: 'CORRESPONDENCE',
      description:
        'Job-specific emails and letters with insurer, insured, and trades. ' +
        'Do NOT file formal quotes, POs, or invoices here — use those categories instead.',
      sortOrder: 7,
      config: { color: '#64748b', retentionDays: YEARS_5 },
    },
    {
      displayName: 'AI Exports',
      slug: 'AI_EXPORTS',
      description:
        'AI-generated artifacts for this job. Do NOT file original site evidence or source claim docs here.',
      sortOrder: 8,
      config: { color: '#ec4899', retentionDays: DAYS_90 },
    },
    {
      displayName: 'Other',
      slug: 'OTHER',
      description:
        'Catch-all for job documents that do not fit another category. Prefer a more specific category when possible.',
      sortOrder: 9,
      config: { color: '#a3a3a3', retentionDays: YEARS_5 },
    },
  ],
};

/** Platform starters seeded for every environment. */
export const PLATFORM_FILESYSTEM_TEMPLATES: SeededFilesystemTemplate[] = [
  COMPANY_FILESYSTEM_TEMPLATE,
  PROJECT_FILESYSTEM_TEMPLATE,
];

/** @deprecated use COMPANY_FILESYSTEM_TEMPLATE — kept for import compatibility during transition */
export const CONSTRUCTION_FILESYSTEM_TEMPLATE = COMPANY_FILESYSTEM_TEMPLATE;
