import { z } from 'zod';

export const AssessmentSourceSchema = z.object({
  company_name: z.string(),
  assessment_name: z.string(),
  status: z.string(),
  job_name: z.string(),
  job_reference: z.string(),

  address_attended: z.string(),
  other_address: z.string(),
  date_booked: z.string(),
  persons_attending: z.string(),
  builder_estimator_name: z.string(),
  builder_estimator_phone: z.string(),
  iag_inspection_required: z.string(),
  insurance_assessor_name: z.string(),
  insurance_assessor_phone: z.string(),
  occupancy_type: z.string(),

  square_metres: z.string(),
  building_age: z.string(),
  building_type: z.string(),
  design_type: z.string(),
  construction: z.string(),
  roof_type: z.string(),
  additional_structures: z.string(),
  other_structures: z.string(),
  squares: z.string(),
  main_roof_damage: z.string(),
  overall_condition_acceptable: z.string(),
  furniture_removal_storage: z.string(),
  detached_garage: z.string(),
  sheds: z.string(),
  swimming_pool: z.string(),
  detached_granny_flat: z.string(),

  habitable: z.string(),
  uninhabitable_reason: z.string(),
  other_uninhabitable_reason: z.string(),

  hazard_pool_fencing: z.string(),
  hazard_pool_fencing_comment: z.string(),
  hazard_electrical_gas: z.string(),
  hazard_electrical_gas_comment: z.string(),
  hazard_sewerage: z.string(),
  hazard_sewerage_comment: z.string(),
  hazard_structural: z.string(),
  hazard_structural_comment: z.string(),
  hazard_other: z.string(),
  safety_hazards: z.string(),
  environmental_hazards: z.string(),
  mould: z.string(),
  asbestos_on_site: z.string(),

  resultant_damage: z.string(),
  cause_of_damage: z.string(),
  damage_caused_by_listed_event: z.string(),
  pre_existing_maintenance_issues: z.string(),
  pre_existing_relate_damage: z.string(),
  maintenance_related_issues: z.string(),
  works_required_to_address_damage: z.string(),

  make_safe: z.string(),
  make_safe_type: z.string(),
  make_safe_completion_date: z.string(),
  date_main_roof_repaired: z.string(),

  temp_accom_required: z.string(),
  temp_accom_estimated_amount: z.string(),
  temp_accom_estimated_duration: z.string(),
  temp_accom_required_immediately: z.string(),
  temp_accom_immediate_estimate_days: z.string(),
  temp_accom_required_during_repairs: z.string(),
  temp_accom_repairs_estimate_days: z.string(),
  temp_repairs_to_make_livable: z.string(),
  work_while_in_accommodation: z.string(),

  specialist_required: z.string(),
  specialist_type: z.string(),

  claim_recommendation: z.string(),
  cost_estimate_for_repairs: z.string(),
  estimated_repair_time: z.string(),
  estimated_repair_duration: z.string(),
  insured_advised: z.string(),
  client_willing_to_proceed: z.string(),
  customer_arranged_repairs: z.string(),
  arranged_repair_comments: z.string(),
  client_discussion: z.string(),
  comments: z.string(),
  variances_of_scope: z.string(),
  builder_licenses: z.string(),

  created_at: z.string(),
  report_date: z.string(),
});
