import { z } from 'zod';

export const AssessmentSourceSchema = z.object({
  company_name: z.string(),
  assessment_name: z.string(),
  status: z.string(),
  job_name: z.string(),
  job_reference: z.string(),

  claim_recommendation: z.string(),
  design_type: z.string(),
  construction: z.string(),
  roof_type: z.string(),
  building_type: z.string(),
  make_safe: z.string(),
  make_safe_type: z.string(),
  squares: z.string(),
  building_age: z.string(),
  square_metres: z.string(),
  date_booked: z.string(),
  overall_condition_acceptable: z.string(),
  iag_inspection_required: z.string(),

  make_safe_completion_date: z.string(),
  main_roof_damage: z.string(),
  date_main_roof_repaired: z.string(),
  habitable: z.string(),
  mould: z.string(),
  asbestos_on_site: z.string(),
  detached_garage: z.string(),
  sheds: z.string(),
  swimming_pool: z.string(),
  detached_granny_flat: z.string(),
  damage_caused_by_listed_event: z.string(),

  hazard_pool_fencing: z.string(),
  hazard_pool_fencing_comment: z.string(),
  hazard_electrical_gas: z.string(),
  hazard_electrical_gas_comment: z.string(),
  hazard_sewerage: z.string(),
  hazard_sewerage_comment: z.string(),
  hazard_structural: z.string(),
  hazard_structural_comment: z.string(),
  hazard_other: z.string(),

  temp_accom_required_immediately: z.string(),
  temp_accom_immediate_estimate_days: z.string(),
  temp_repairs_to_make_livable: z.string(),
  temp_accom_required_during_repairs: z.string(),
  temp_accom_repairs_estimate_days: z.string(),
  work_while_in_accommodation: z.string(),

  client_discussion: z.string(),
  resultant_damage: z.string(),
  cause_of_damage: z.string(),
  maintenance_related_issues: z.string(),
  comments: z.string(),
  variances_of_scope: z.string(),

  created_at: z.string(),
  report_date: z.string(),
});
