import { Global, Module } from '@nestjs/common';
import { DrizzleModule } from './drizzle.module';
import {
  ClaimsRepository,
  LookupsRepository,
  JobsRepository,
  ContactsRepository,
  ClaimContactsRepository,
  ClaimAssigneesRepository,
  VendorsRepository,
  QuotesRepository,
  InvoicesRepository,
  PurchaseOrdersRepository,
  TasksRepository,
  MessagesRepository,
  AppointmentsRepository,
  ReportsRepository,
  AttachmentsRepository,
  InboundWebhookEventsRepository,
  UsersRepository,
  IntegrationConnectionsRepository,
  ExternalObjectsRepository,
  ExternalObjectVersionsRepository,
  ExternalLinksRepository,
  ExternalProcessingLogRepository,
  ExternalEventAttemptsRepository,
  WorkOrdersRepository,
  RfqsRepository,
  ProposalsRepository,
  BillsRepository,
  JobContactsRepository,
  CatalogsRepository,
  CatalogItemTypesRepository,
  CatalogCategoriesRepository,
  CatalogItemsRepository,
  CatalogAssemblyComponentsRepository,
  JournalsRepository,
  JournalPagesRepository,
  JournalPageAttachmentsRepository,
  NotificationsRepository,
} from './repositories';

const repositories = [
  ClaimsRepository,
  LookupsRepository,
  JobsRepository,
  ContactsRepository,
  ClaimContactsRepository,
  ClaimAssigneesRepository,
  VendorsRepository,
  QuotesRepository,
  InvoicesRepository,
  PurchaseOrdersRepository,
  TasksRepository,
  MessagesRepository,
  AppointmentsRepository,
  ReportsRepository,
  AttachmentsRepository,
  InboundWebhookEventsRepository,
  UsersRepository,
  IntegrationConnectionsRepository,
  ExternalObjectsRepository,
  ExternalObjectVersionsRepository,
  ExternalLinksRepository,
  ExternalProcessingLogRepository,
  ExternalEventAttemptsRepository,
  WorkOrdersRepository,
  RfqsRepository,
  ProposalsRepository,
  BillsRepository,
  JobContactsRepository,
  CatalogsRepository,
  CatalogItemTypesRepository,
  CatalogCategoriesRepository,
  CatalogItemsRepository,
  CatalogAssemblyComponentsRepository,
  JournalsRepository,
  JournalPagesRepository,
  JournalPageAttachmentsRepository,
  NotificationsRepository,
];

@Global()
@Module({
  imports: [DrizzleModule],
  providers: [...repositories],
  exports: [...repositories],
})
export class DatabaseModule {}
